
package br.edu.facthus.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraSoap", targetNamespace = "http://ws.facthus.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraSoap {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soma", targetNamespace = "http://ws.facthus.edu.br/", className = "br.edu.facthus.client.Soma")
    @ResponseWrapper(localName = "somaResponse", targetNamespace = "http://ws.facthus.edu.br/", className = "br.edu.facthus.client.SomaResponse")
    public int soma(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
